# Generated by Django 4.1.6 on 2023-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
