# Generated by Django 4.1.6 on 2023-02-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_eventtime_day_alter_eventtime_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtime",
            name="day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventtime",
            name="hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventtime",
            name="minute",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventtime",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventtime",
            name="second",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventtime",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
