# Generated by Django 4.1.5 on 2023-01-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('event', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Convict',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.convict')),
            ],
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MaritalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OffenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PunishmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RacialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkForPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfMutilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_conviction', models.BooleanField(null=True)),
                ('number', models.IntegerField()),
                ('parole_violation', models.BooleanField(null=True)),
                ('new_term', models.BooleanField(null=True)),
                ('outcome', models.CharField(max_length=100)),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_days', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('method', models.ManyToManyField(null=True, related_name='punishment_method', to='register_and_ledger.punishmentmethod')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment_prison', to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pardon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('ed_by', models.ManyToManyField(null=True, related_name='pardoner', to='person.person')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_days', models.IntegerField()),
                ('convict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convict_lease', to='register_and_ledger.convict')),
                ('end_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_end_date', to='event.eventtime')),
                ('lessee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessee_lease', to='register_and_ledger.company')),
                ('start_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_start_date', to='event.eventtime')),
                ('where_after', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=100)),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusty', models.BooleanField(null=True)),
                ('wounded', models.BooleanField(null=True)),
                ('recaptured', models.BooleanField(null=True)),
                ('surrender', models.BooleanField(null=True)),
                ('returned', models.BooleanField(null=True)),
                ('same_day', models.BooleanField(null=True)),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=100)),
                ('killed', models.BooleanField(null=True)),
                ('suicide', models.BooleanField(null=True)),
                ('disease', models.BooleanField(null=True)),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convict_numer', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.birth')),
                ('convictions', models.ManyToManyField(null=True, related_name='convict_record', to='register_and_ledger.conviction')),
                ('death', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.death')),
                ('escapes', models.ManyToManyField(null=True, related_name='convict_record', to='register_and_ledger.escape')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('record_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventtime')),
            ],
        ),
        migrations.AddField(
            model_name='conviction',
            name='complexion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.racialcategory'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='convict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.convict'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='expires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conviction_expires', to='event.eventtime'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='marital_relations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.maritalcategory'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='offence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_and_ledger.offencecategory'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='pardons',
            field=models.ManyToManyField(null=True, related_name='parents', to='register_and_ledger.pardon'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conviction_place', to='place.place'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='place_of_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='place.place'),
        ),
        migrations.AddField(
            model_name='conviction',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conviction_time', to='event.eventtime'),
        ),
    ]
