# Generated by Django 4.1.5 on 2023-01-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convictrecord',
            name='convictions',
        ),
        migrations.AddField(
            model_name='conviction',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conviction', to='register_and_ledger.convictrecord'),
        ),
        migrations.AlterField(
            model_name='convictrecord',
            name='escapes',
            field=models.ManyToManyField(null=True, related_name='escapee_record', to='register_and_ledger.escape'),
        ),
    ]
