# Generated by Django 4.1.5 on 2023-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0002_remove_convictrecord_convictions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conviction',
            name='convict',
        ),
    ]
