# Generated by Django 4.1.5 on 2023-01-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0003_remove_conviction_convict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convictrecord',
            name='escapes',
        ),
        migrations.AddField(
            model_name='escape',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escape', to='register_and_ledger.convictrecord'),
        ),
    ]
