# Generated by Django 4.1.5 on 2023-01-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0004_remove_convictrecord_escapes_escape_convict_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='register_and_ledger.convictrecord'),
        ),
        migrations.AddField(
            model_name='punishment',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punishment', to='register_and_ledger.convictrecord'),
        ),
    ]
