# Generated by Django 4.1.5 on 2023-01-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0005_lease_convict_record_punishment_convict_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalization', to='register_and_ledger.convictrecord'),
        ),
    ]
