# Generated by Django 4.1.5 on 2023-01-30 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('register_and_ledger', '0008_pardon_conviction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pardon',
            name='ed_by',
        ),
        migrations.AddField(
            model_name='pardon',
            name='pardoner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pardon', to='person.person'),
        ),
    ]
