# Generated by Django 4.1.5 on 2023-01-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_ledger', '0009_remove_pardon_ed_by_pardon_pardoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforprison',
            name='convict_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_for_prison', to='register_and_ledger.convictrecord'),
        ),
    ]
