# Generated by Django 4.1.6 on 2023-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
        ("register_and_ledger", "0012_alter_birth_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="birth",
            name="birth_parents",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="parents", to="person.person"
            ),
        ),
        migrations.AlterField(
            model_name="death",
            name="disease",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="death",
            name="killed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="death",
            name="suicide",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospitalization",
            name="cause",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
