# Generated by Django 4.1.6 on 2023-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "register_and_ledger",
            "0013_birth_birth_parents_alter_death_disease_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="death",
            name="cause",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
