# Generated by Django 4.1.6 on 2023-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="bounds",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
